
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
# Ativar Option como Alt
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[keyboard]
bindings = [

  { key = "Back", mods = "Alt", chars = "\u007f" },      # Option + Backspace (Apagar palavra atrás)
  { key = "Delete", mods = "Alt", chars = "\u001b[3~" }, # Option + Delete (Apagar palavra à frente)

  # Option + Left / Right → Mover entre palavras
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },

  # Command + Left / Right → Ir para o início/fim da linha
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },

  # Command + Up / Down → Primeiro e último comando no histórico
  { key = "Up", mods = "Command", chars = "\u001b[5~" },
  { key = "Down", mods = "Command", chars = "\u001b[6~" },

  # brackets
  { key = "8", mods = "Alt", chars = "[" },
  { key = "9", mods = "Alt", chars = "]" },
  { key = "8", mods = "Alt|Shift", chars = "{" },
  { key = "9", mods = "Alt|Shift", chars = "}" },

  #special symbols
  { key = "2", mods = "Alt", chars = "@" },
]

[general]
import = ["~/.config/alacritty/themes/themes/github_dark.toml"]
